name: rec_movies_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/posters/poster1.jpg
    - assets/posters/poster2.jpg
    - assets/posters/poster3.jpg
    - assets/posters/poster4.jpg
    - assets/posters/poster5.jpg
    - assets/avatars/avatar1.jpg
    - assets/avatars/avatar2.jpg
    - assets/avatars/avatar3.jpg
    - assets/avatars/avatar4.jpg
    - assets/avatars/avatar5.jpg